name: LÖVE Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: love-build
        uses: nhartland/love-build@v1-beta2
        with:
          app_name: Oops You Started An Intergalactic War
          love_version: '11.3'
          source_dir: src
      - uses: actions/upload-artifact@v1
        with:
          name: macos-build
          path: '${{ steps.love-build.outputs.macos-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win32-build
          path: '${{ steps.love-build.outputs.win32-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win64-build
          path: '${{ steps.love-build.outputs.win64-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: love-build
          path: '${{ steps.love-build.outputs.love-filename }}'
      - name: itch.io upload (win64)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: oops-you-started-an-intergalactic-war
          ITCH_USER: monkeymad2
          PACKAGE: '${{ steps.love-build.outputs.win64-filename }}'
      - name: itch.io upload (mac)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: mac
          ITCH_GAME: oops-you-started-an-intergalactic-war
          ITCH_USER: monkeymad2
          PACKAGE: '${{ steps.love-build.outputs.macos-filename }}'
      - name: itch.io upload (löve)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: love
          ITCH_GAME: oops-you-started-an-intergalactic-war
          ITCH_USER: monkeymad2
          PACKAGE: '${{ steps.love-build.outputs.love-filename }}'
