name: LÖVE Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: love-build
        uses: nhartland/love-build@v1-beta2
        with:
          app_name: Oops You Started An Intergalatic War
          love_version: '11.3'
          source_dir: src
      - uses: actions/upload-artifact@v1
        with:
          name: macos-build
          path: '${{ steps.love-build.outputs.macos-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win32-build
          path: '${{ steps.love-build.outputs.win32-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win64-build
          path: '${{ steps.love-build.outputs.win64-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: love-build
          path: '${{ steps.love-build.outputs.love-filename }}'
