name: LÖVE Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: love-build
        uses: nhartland/love-build@v1-beta2
        with:
          app_name: Oops You Started An Intergalactic War
          love_version: '11.3'
          source_dir: src
      - uses: actions/upload-artifact@v1
        with:
          name: macos-build
          path: '${{ steps.love-build.outputs.macos-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win32-build
          path: '${{ steps.love-build.outputs.win32-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: win64-build
          path: '${{ steps.love-build.outputs.win64-filename }}'
      - uses: actions/upload-artifact@v1
        with:
          name: love-build
          path: '${{ steps.love-build.outputs.love-filename }}'
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: oops-you-started-an-intergalactic-war
          ITCH_USER: monkeymad2
          PACKAGE: '${{ steps.love-build.outputs.win64-filename }}'
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: mac
          ITCH_GAME: oops-you-started-an-intergalactic-war
          ITCH_USER: monkeymad2
          PACKAGE: '${{ steps.love-build.outputs.macos-filename }}'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (love)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '${{ steps.love-build.outputs.love-filename }}'
          asset_name: love-build.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (mac)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '${{ steps.love-build.outputs.macos-filename }}'
          asset_name: mac-build.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (win32)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '${{ steps.love-build.outputs.win32-filename }}'
          asset_name: win32-build.zip
          asset_content_type: application/zip
      - name: Upload Release Asset (win64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: '${{ steps.love-build.outputs.win64-filename }}'
          asset_name: win64-build.zip
          asset_content_type: application/zip
